title: BuiltByTAGM
logo: docs/assets/LOGOTAGM.png
Description: AI Systems for FinTech Alpha | Gen AI, Python, Vector DBs, LLMs, Quantum Machine Learning (QML) 
#show_downloads: true
theme: jekyll-theme-minimal
