title: BuiltByTAGM
logo: docs/assets/LOGOTAGM.png
description: AI Systems for FinTech Alpha | Gen AI, Python, Vector DBs, LLMs, Quantum Machine Learning (QML) |
Photo: docs/assets/finaltm.jpg
#show_downloads: true
theme: jekyll-theme-minimal
